### ISSUE TITLE
add read.md file

### ISSUE THREAD

**Issue by kavindyasinthasilva** [skysoftlk/sky-silva-Nirmanee#1]
step
# 1 code tab click
 2  create new file  click - add name read.md

assingess click your profile -right side

**Comment by Nirmanee** [comment]
Thankyou!

**Comment by kavindyasinthasilva** [comment]
#congratulations
![68747470733a2f2f6f63746f6465782e6769746875622e636f6d2f696d616765732f62656e65766f636174732e6a7067](https://user-images.githubusercontent.com/49961072/68082599-d10c8280-fe44-11e9-81fb-08fbea6c4941.jpg)
